name: crossdrop
description: "Android Nearby Share implementation for Flutter"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  adwaita: ^1.1.0
  bonsoir: ^5.1.11
  cryptography: ^2.7.0
  device_info_plus: ^11.3.3
  fixnum: ^1.1.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.0.0
  mime: ^2.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  pointycastle: ^4.0.0
  protobuf: ^4.0.0
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  system_tray: ^2.0.3
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  window_manager: ^0.4.3

dependency_overrides:
  uuid: ^3.0.6

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/sf_symbols/
    - assets/icons/

flutter_launcher_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"
  web:
    generate: false
  windows:
    generate: true
    icon_size: 128 # min:48, max:256, default: 48
    image_path: "assets/icons/app_icon.png"
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"
