name: crossdrop
description: "Android Nearby Share implementation for Flutter"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  adwaita: ^1.1.0
  bonsoir: ^5.1.10
  cryptography: ^2.7.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.0.0
  fixnum: ^1.1.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_local_notifications: ^17.2.3
  multicast_dns: ^0.3.2+7
  nsd: ^3.0.0
  pointycastle: ^3.9.1
  protobuf: ^3.1.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  system_tray: ^2.0.3
  uuid: ^4.5.1
  window_manager:
    git:
      url: https://github.com/leanflutter/window_manager.git
      ref: main

dependency_overrides:
  uuid: ^3.0.6

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/sf_symbols/
    - assets/icons/
flutter_launcher_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"
  web:
    generate: false
  windows:
    generate: true
    icon_size: 128 # min:48, max:256, default: 48
    image_path: "assets/icons/app_icon.png"
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"
